//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekTarifi3
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeriBildirimTablaso
    {
        public int Geri_BildirimID { get; set; }
        public int Kullanici_ID { get; set; }
        public string Acıklama { get; set; }
    }
}
