//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekTarifi3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HataTablosu
    {
        public int HataID { get; set; }
        public string Hata_Adress { get; set; }
        public string Hata_Kodu { get; set; }
        public string Hata_Aktiflik { get; set; }
        public string Hata_Detay { get; set; }
        public System.DateTimeOffset Hata_Zamanı { get; set; }
    }
}
