//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekTarifi3
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciTablosu
    {
        public int Kullanici_ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Cinsiyeti { get; set; }
        public string Email { get; set; }
        public string kullaniciadi { get; set; }
        public string Sifre { get; set; }
    }
}
